[phases.setup]
nixPkgs = ['python3', 'libGL']  # tambahkan python3

[phases.install]
cmds = ['python3 -m pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.start]
cmd = 'gunicorn app:app'