[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["python311Full", "libGL"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn app:app"
